/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118315-g4f3c9f2f03-20250116"
#endif /* AVUTIL_FFVERSION_H */
